services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:10
    command: -connectRetries=60 migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/demo
      FLYWAY_USER: demo
      FLYWAY_PASSWORD: demo
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - postgres

  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - ./jenkins:/var/jenkins_home/workspace
