services:

  mysql:
    image: mysql:8.1
    container_name: airflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
      - "3306:3306"

  oracle:
    image: gvenzl/oracle-xe
    container_name: airflow-oracle
    environment:
      ORACLE_PASSWORD: yourStrongPassword
    ports:
      - "1521:1521"

  airflow-init-mysql:
    build: ./airflow
    container_name: airflow-init
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://demo:demo@mysql:3306/demo
    command: >
      bash -c "airflow db migrate &&
               airflow users create -u admin -p admin -f Admin -l User -r Admin -e admin@example.com; "
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./flyway/sql:/opt/airflow/flyway/sql

  airflow-init:
#    build: ./airflow
    build: .
    container_name: airflow-init
    depends_on:
      - oracle
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-oracle python-oracledb"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: oracle://system:yourStrongPassword@oracle:1521/XE
    command: >
      bash -c "airflow db migrate &&
               airflow users create -u admin -p admin -f Admin -l User -r Admin -e admin@example.com; "
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./flyway/sql:/opt/airflow/flyway/sql
      - ./plugins:/opt/airflow/plugins

  airflow:
    build: ./airflow
    container_name: airflow
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__CORE__TEST_CONNECTION: "enabled"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://demo:demo@mysql:3306/demo
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      LD_LIBRARY_PATH: /opt/oracle/instantclient_19_21
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./flyway/sql:/opt/airflow/flyway/sql
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: ./airflow
    container_name: airflow-scheduler
    depends_on:
      - airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://demo:demo@mysql:3306/demo
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./flyway/sql:/opt/airflow/flyway/sql
    command: scheduler
