pipeline {
  agent any

  stages {
    stage('Detect change') {
      steps {
        echo "Simulating approved Git merge"
      }
    }

    stage('Trigger Airflow') {
      steps {
        sh """
        curl -X POST http://airflow:8080/api/v1/dags/ebs_flyway_deploy/dagRuns \
          -H "Content-Type: application/json" \
          -d '{}'
        """
      }
    }
  }
}
